#!/bin/sh
#

if ! grep -q "access\.log" /etc/nginx/conf.d/http.conf; then
    sed -i 's/$host.log/access.log/' /etc/nginx/conf.d/http.conf
fi

if [ ! -e /etc/nginx/http.d/auth_basic ]; then
    echo admin:$(echo $REPORT_PWD | openssl passwd -stdin -apr1) > /etc/nginx/http.d/auth_basic
fi
