#!/bin/sh -e
#

chmod +x `grep -rl '^#!/bin' /ifs`

# install apps

wkit geoip-install

apk add --no-cache openssh goaccess
rm -f /etc/goaccess/goaccess.conf

cp -a /ifs/etc /

# clean system

rm -r /ifs
