#!/bin/sh
#
# Nginx Log Conversion table:
#   $time_local         %d:%t %^
#   $host               %v
#   $http_host          %v
#   $remote_addr        %h
#   $request_time       %T
#   $request_method     %m
#   $request_uri        %U
#   $server_protocol    %H
#   $request            %r
#   $status             %s
#   $body_bytes_sent    %b
#   $bytes_sent         %b
#   $http_referer       %R
#   $http_user_agent    %u
#

#################################################

export GAPATH=/var/www/default

if ! type goaccess >/dev/null 2>&1; then

########

apk add goaccess

cat <<EOF >/etc/goaccess/goaccess.conf
# Date/Time Format Option
time-format %T
date-format %d/%b/%Y
log_format %h - %e [%d:%t %^] "%r" %s %b "%R" "%u" "%^" %^ %^ %^ %T
# Server Options
port 8484
daemonize true
real-time-html true
ws-url ws://localhost:8484/report/d
# GeoIP Options
geoip-database /usr/share/geoip/city-lite.mmdb
# Persistence Options
db-path $GAPATH/gadata
EOF

########

fi

#################################################

export NGXLOG=/var/log/nginx/access.log

if ! grep -q "access\.log" /etc/nginx/conf.d/http.conf; then
    sed -i 's/$host.log/access.log/' /etc/nginx/conf.d/http.conf
    wkit nginx reload
fi

#################################################

mkdir -p $GAPATH/gadata $GAPATH/report

goaccess $NGXLOG \
    --output=$GAPATH/report/index.html
